server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file://Users/davidcryer/Projects/Web/config
management:
  security:
    enabled: false